version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "ASM"
      POSTGRES_USER: "admin"
    ports:
      - 8080:8080